// Test generated by RoostGPT for test spotifyApi-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class DbQueryStatus_getMessage_cebf167bb8_Test {

    private DbQueryStatus dbQueryStatus;

    @BeforeEach
    public void setup() {
        dbQueryStatus = new DbQueryStatus("Test message", DbQueryExecResult.QUERY_OK);
    }

    @Test
    public void testGetMessage_Success() {
        String expectedMessage = "Test message";
        String actualMessage = dbQueryStatus.getMessage();
        assertEquals(expectedMessage, actualMessage, "Expected message does not match actual message");
    }

    @Test
    public void testGetMessage_Failure() {
        String unexpectedMessage = "Unexpected message";
        String actualMessage = dbQueryStatus.getMessage();
        assertNotEquals(unexpectedMessage, actualMessage, "Unexpected message should not match actual message");
    }
}
