// Test generated by RoostGPT for test spotifyApi-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.songmicroservice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class DbQueryStatus_DbQueryStatus_03cbc2162e_Test {

    @Mock
    DbQueryExecResult dbQueryExecResult;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testDbQueryStatus_Success() {
        when(dbQueryExecResult.getResult()).thenReturn("Success");

        DbQueryStatus dbQueryStatus = new DbQueryStatus("Success", dbQueryExecResult);

        assertEquals("Success", dbQueryStatus.getMessage());
        assertEquals("Success", dbQueryStatus.getdbQueryExecResult().getResult());
    }

    @Test
    public void testDbQueryStatus_Failure() {
        when(dbQueryExecResult.getResult()).thenReturn("Failure");

        DbQueryStatus dbQueryStatus = new DbQueryStatus("Failure", dbQueryExecResult);

        assertEquals("Failure", dbQueryStatus.getMessage());
        assertEquals("Failure", dbQueryExecResult.getResult());
    }
}
