// Test generated by RoostGPT for test spotifyApi-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.songmicroservice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

@ExtendWith(MockitoExtension.class)
public class Song_setSongName_6089d3ca93_Test {

    @InjectMocks
    private Song song;

    @BeforeEach
    public void setup() {
        song = new Song();
    }

    @Test
    public void testSetSongName() {
        String songName = "Test Song";
        song.setSongName(songName);
        assertEquals(songName, song.getSongName(), "Song name should be set correctly");
    }

    @Test
    public void testSetSongNameWithNull() {
        assertThrows(NullPointerException.class, () -> song.setSongName(null), "Should throw NullPointerException when song name is null");
    }
}
